import type { Metadata } from "next";
import "./globals.css";

import Header from "./components/Header";
import { ToastContainer } from "react-toastify";
import AuthGuard from "./components/AuthGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-roboto min-h-screen bg-slate-900 pb-20 text-sm text-white">
        <Header />

        <main className="container mx-auto max-w-[1000px]">
          <AuthGuard>{children}</AuthGuard>
        </main>

        <ToastContainer position="bottom-right" autoClose={2000} />
      </body>
    </html>
  );
}
